package com.chains.pwqxfwjk.model;

import java.util.Calendar;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FaultStatisticsDetail generated by hbm2java
 */
@Entity
@Table(name = "fault_statistics_detail")
public class FaultStatisticsDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String category;
	private String faultDevice;
	private String repairContent;
	private String faultDeviceVoltageLevel;
	private String faultCategory;
	private String reportCustomerName;
	private String reportCustomerNumber;
	private Date reportTime;
	private String handlerUser;
	private Date sendMissionTime;
	private String performer;
	private Date performerArriveTime;
	private Date repairEndtime;
	private Boolean arriveTimeout;
	private Boolean repairTimeout;
	private Boolean customerDevice;
	private Date reviewTime;
	private String reviewPerson;
	private Boolean satisfaction;
	private String descriptor;
	private String missionId;
	private String picPath;

	public FaultStatisticsDetail() {
	}

	public FaultStatisticsDetail(Integer id, String category, String faultDevice, String repairContent,
			String faultDeviceVoltageLevel, String faultCategory, String reportCustomerName,
			String reportCustomerNumber, Date reportTime, String handlerUser, Date sendMissionTime, String performer,
			Date performerArriveTime, Date repairEndtime, Boolean customerDevice, Date reviewTime, String reviewPerson,
			Boolean satisfaction, String descriptor, String missionId, String picPath) {
		super();
		this.id = id;
		this.category = category;
		this.faultDevice = faultDevice;
		this.repairContent = repairContent;
		this.faultDeviceVoltageLevel = faultDeviceVoltageLevel;
		this.faultCategory = faultCategory;
		this.reportCustomerName = reportCustomerName;
		this.reportCustomerNumber = reportCustomerNumber;
		this.reportTime = reportTime;
		this.handlerUser = handlerUser;
		this.sendMissionTime = sendMissionTime;
		this.performer = performer;
		this.performerArriveTime = performerArriveTime;
		this.repairEndtime = repairEndtime;
		this.customerDevice = customerDevice;
		this.reviewTime = reviewTime;
		this.reviewPerson = reviewPerson;
		this.satisfaction = satisfaction;
		this.descriptor = descriptor;
		this.missionId = missionId;
		this.picPath = picPath;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category", length = 16)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "fault_device", length = 120)
	public String getFaultDevice() {
		return this.faultDevice;
	}

	public void setFaultDevice(String faultDevice) {
		this.faultDevice = faultDevice;
	}

	@Column(name = "repair_content", length = 120)
	public String getRepairContent() {
		return this.repairContent;
	}

	public void setRepairContent(String repairContent) {
		this.repairContent = repairContent;
	}

	@Column(name = "fault_device_voltage_level", length = 10)
	public String getFaultDeviceVoltageLevel() {
		return this.faultDeviceVoltageLevel;
	}

	public void setFaultDeviceVoltageLevel(String faultDeviceVoltageLevel) {
		this.faultDeviceVoltageLevel = faultDeviceVoltageLevel;
	}

	@Column(name = "fault_category", length = 100)
	public String getFaultCategory() {
		return this.faultCategory;
	}

	public void setFaultCategory(String faultCategory) {
		this.faultCategory = faultCategory;
	}

	@Column(name = "report_customer_name", length = 30)
	public String getReportCustomerName() {
		return this.reportCustomerName;
	}

	public void setReportCustomerName(String reportCustomerName) {
		this.reportCustomerName = reportCustomerName;
	}

	@Column(name = "report_customer_number", length = 30)
	public String getReportCustomerNumber() {
		return this.reportCustomerNumber;
	}

	public void setReportCustomerNumber(String reportCustomerNumber) {
		this.reportCustomerNumber = reportCustomerNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "report_time", length = 19)
	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "handler_user", length = 18)
	public String getHandlerUser() {
		return this.handlerUser;
	}

	public void setHandlerUser(String handlerUser) {
		this.handlerUser = handlerUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_mission_time", length = 19)
	public Date getSendMissionTime() {
		return this.sendMissionTime;
	}

	public void setSendMissionTime(Date sendMissionTime) {
		this.sendMissionTime = sendMissionTime;
	}

	@Column(name = "performer", length = 20)
	public String getPerformer() {
		return this.performer;
	}

	public void setPerformer(String performer) {
		this.performer = performer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "performer_arrive_time", length = 19)
	public Date getPerformerArriveTime() {
		return this.performerArriveTime;
	}

	public void setPerformerArriveTime(Date performerArriveTime) {
		this.performerArriveTime = performerArriveTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "repair_endtime", length = 19)
	public Date getRepairEndtime() {
		return this.repairEndtime;
	}

	public void setRepairEndtime(Date repairEndtime) {
		this.repairEndtime = repairEndtime;
	}

	@Column(name = "arrive_timeout", length = 1)
	@org.hibernate.annotations.Type(type="yes_no")
	public Boolean getArriveTimeout() {
		return this.arriveTimeout;
	}

	public void setArriveTimeout(Boolean arriveTimeout) {
		this.arriveTimeout = arriveTimeout;
	}

	@Column(name = "repair_timeout", length = 1)
	@org.hibernate.annotations.Type(type="yes_no")
	public Boolean getRepairTimeout() {
		return this.repairTimeout;
	}

	public void setRepairTimeout(Boolean repairTimeout) {
		this.repairTimeout = repairTimeout;
	}

	@Column(name = "customer_device", length = 1)
	@org.hibernate.annotations.Type(type="yes_no")
	public Boolean getCustomerDevice() {
		return this.customerDevice;
	}

	public void setCustomerDevice(Boolean customerDevice) {
		this.customerDevice = customerDevice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	@Column(name = "review_person", length = 20)
	public String getReviewPerson() {
		return this.reviewPerson;
	}

	public void setReviewPerson(String reviewPerson) {
		this.reviewPerson = reviewPerson;
	}

	@Column(name = "satisfaction", length = 1)
	@org.hibernate.annotations.Type(type="yes_no")
	public Boolean getSatisfaction() {
		return this.satisfaction;
	}

	public void setSatisfaction(Boolean satisfaction) {
		this.satisfaction = satisfaction;
	}

	@Column(name = "descriptor", length = 400)
	public String getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	@Column(name = "mission_id", length=40)
	public String getMissionId() {
		return this.missionId;
	}

	public void setMissionId(String missionId) {
		this.missionId = missionId;
	}

	@Column(name = "pic_path", length=400)
	public String getPicPath() {
		return picPath;
	}

	public void setPicPath(String picPath) {
		this.picPath = picPath;
	}
	
	/**
	 * 判断抢修时间是否超时
	 */
	public void whetherArriveTimeout() {
		if(this.getSendMissionTime() != null && this.getPerformerArriveTime() != null) {
			Calendar calendar = Calendar.getInstance();
			calendar.setTime(this.getSendMissionTime());
			calendar.add(Calendar.MINUTE, 90);
			
			if(calendar.getTime().compareTo(this.getPerformerArriveTime()) > 0) {
				this.setArriveTimeout(false);
			}else {
				this.setArriveTimeout(true);
			}
		}
	}
}
